[skip ci] auto update files with upstream.

diff --git a/src/tailscale.initd b/src/tailscale.initd
--- a/src/tailscale.initd
+++ b/src/tailscale.initd
@@ -1,20 +1,32 @@
 #!/sbin/openrc-run
 
-TAILSCALED_LOGFILE="${TAILSCALED_LOGFILE:-/var/log/${RC_SVCNAME}d.log}"
-TAILSCALED_PORT="${TAILSCALED_PORT:-41641}"
+# Uppercase variables are for backward compatibility (Alpine <3.21).
+: ${capabilities="^cap_net_admin,cap_net_raw"}
+: ${command_user:="root:tailscale"}
+: ${logfile="${TAILSCALED_LOGFILE:-"/var/log/tailscaled.log"}"}
+: ${no_logs_no_support:=no}
+: ${port:="${TAILSCALED_PORT:-41641}"}
+: ${socket:="/run/tailscale/tailscaled.sock"}
+: ${statedir:="/var/lib/tailscale"}
+: ${supervisor="supervise-daemon"}
+: ${verbose:=0}
 
-supervisor=supervise-daemon
-
-name="tailscaled"
 command="/usr/sbin/tailscaled"
-command_args="--state=/var/lib/tailscale/tailscaled.state --port ${TAILSCALED_PORT} ${TAILSCALED_OPTS} >>${TAILSCALED_LOGFILE} 2>&1"
+command_args="--socket=$socket --state=$statedir/tailscaled.state --port=$port --verbose=$verbose $TAILSCALED_OPTS $command_args"
+command_background=yes
+pidfile="/run/$RC_SVCNAME.pid"
 
-output_log=${TAILSCALED_LOGFILE}
-error_log=${TAILSCALED_LOGFILE}
+output_log="$logfile"
+error_log="$logfile"
 
-pidfile="/run/tailscaled.pid"
-respawn_delay=5
-respawn_max=0
+# Alpine uses the nf_tables backend by default (see #14058). The "auto"
+# heuristic doesn't work correctly, it prefers iptables (and fails due to
+# missing modules) even when nftables are in use.
+# See https://tailscale.com/kb/1294/firewall-mode
+export TS_DEBUG_FIREWALL_MODE="${firewall_mode:-"nftables"}"
+# The purpose of this is to make tailscaled use our resolvconf wrapper that
+# executes /usr/sbin/resolvconf via doas.
+export PATH="/usr/libexec/tailscale:$PATH"
 
 depend() {
 	need net
@@ -23,5 +35,8 @@ depend() {
 }
 
 start_pre() {
-	checkpath -f -m 0644 -o root:root "${TAILSCALED_LOGFILE}"
+	yesno "$no_logs_no_support" && command_args="$command_args --no-logs-no-support"
+
+	checkpath -f -m 0640 -o "$command_user" "$logfile" || return 1
+	checkpath -d -m 0755 -o "$command_user" "${socket%/*}"
 }
